---

num_features: 9
use_time_horizon: False
horizon: 10
days_forward: 1
end_split: 30

return_lowest_val_loss: False

models:
  - model: lstm
    hidden_size: 50
    dropout: 0.4
    learning_rate: 0.0016
    batch_size: 16
    num_epochs: 100
    shuffle: True

  - model: gru
    hidden_size: 50
    dropout: 0.4
    learning_rate: 0.0008
    batch_size: 16
    num_epochs: 100
    shuffle: True

  - model: mlp
    hidden_size: 4
    learning_rate: 0.001 #0.001
    batch_size: 8
    num_epochs: 100
    shuffle: True