---

num_features: 9
use_time_horizon: False
horizon: 20
days_forward: 1
end_split: 30

return_lowest_val_loss: False

models:
  - model: lstm
    hidden_size: 60
    dropout: 0.2
    learning_rate: 0.002
    batch_size: 16
    num_epochs: 250
    shuffle: True

  - model: gru
    hidden_size: 50
    dropout: 0.4
    learning_rate: 0.0008
    batch_size: 16
    num_epochs: 150
    shuffle: True

  - model: mlp
    hidden_size: 40
    learning_rate: 0.002 #0.001
    batch_size: 2
    num_epochs: 2000
    shuffle: True